# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Power OS Contributors

[package]
name = "power-os-migrations"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
sqlx = { version = "0.8", default-features = false, features = ["runtime-tokio", "postgres", "tls-native-tls"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
