# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Power OS Contributors

[package]
name = "power-os-api"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
axum = "0.7"
power-os-domain = { path = "../domain" }
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
