# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Power OS Contributors

[package]
name = "power-os-domain"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
serde = { version = "1", features = ["derive"] }
sqlx = { version = "0.8", default-features = false, features = ["postgres", "uuid"] }
uuid = { version = "1", features = ["serde", "v4"] }
rust_decimal = { version = "1", features = ["serde", "db-postgres"] }
